name: Publish package to GitHub Packages

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Compile and Test code
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Set env
        run: echo "{VERSION}=$(echo ${GITHUB_REF:11})" >> "$GITHUB_ENV"
      - name: Publish with Gradle
        run: ./gradlew :publishAllPublicationsToGithubRepository --no-daemon
        env:
          ORG_GRADLE_PROJECT_githubPackagesUsername: ${{ github.actor }}
          ORG_GRADLE_PROJECT_githubPackagesPassword: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ VERSION }}