name: Publish package to GitHub Packages

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Compile and Test code
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Set env
        run: echo "{VERSION}=$(echo ${GITHUB_REF:1})" >> "$GITHUB_ENV"
      - name: Print env
        run: echo "$VERSION"
      - name: Publish with Gradle
        run: ./gradlew :publish --no-daemon
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}